modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/abigailfails/HelpfulHitboxes/issues"
license = "https://github.com/abigailfails/HelpfulHitboxes/blob/main/LICENSE"

[[mods]]
modId = "helpfulhitboxes"
version = "${version}"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/helpful-hitboxes"
logoFile = "helpfulhitboxes.png"
displayName = "Helpful Hitboxes"
authors = "abigailfails"
description = '''
Makes the visual hitbox of certain small blocks larger when you're holding a block of that type, to help with building.
'''

[[mods]]
modId = "jacksonsmixinhackerythisshouldnotbeloaded"
version = "1.0"
displayName = "Mixin Hack"
description = "This mod shouldn't be loaded (fake news mod), but because of a bug so we have to resort to this. :blobtroll:"

[[dependencies.helpfulhitboxes]]
modId = "forge"
mandatory = true
versionRange = "[41.0.94,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.helpfulhitboxes]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"